### ISSUE TITLE
An error occurred: cannot access local variable 'safetensor_dl_loc' where it is not associated with a value

### ISSUE THREAD

**Issue by ghostnyambit** [kevkid/gguf_gui#4]
![Screenshot (2)](https://github.com/user-attachments/assets/bbf33f86-b84d-45ac-9ab4-d06de6565e3a)

Any solutions please?

**Comment by RaemyS** [comment]
had that as well...  in main.py, the variable `safetensor_dl_loc` is only defined inside the try block with the snapshot_download function. If there is an error, the except does only print the error but the program runs furhter and tries to get the value from `safetensor_dl_loc`, which is not defined at that point.

Maybe the error handling should be improved here the get at least a more helpful message for the user.

After all, this is a usage error and occurs, if your entered directory path or repo is not available on hugging face.
