### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_cpp'

### ISSUE THREAD

**Issue by skyline9394** [kevkid/gguf_gui#7]
(base) sky@sky-VMware-Virtual-Platform:~/Desktop$ cd llama.cpp
(base) sky@sky-VMware-Virtual-Platform:~/Desktop/llama.cpp$ streamlit run main.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.192.130:8501

2024-10-26 17:02:45.326 Uncaught app exception
Traceback (most recent call last):
  File "/home/sky/anaconda3/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/sky/anaconda3/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/sky/Desktop/llama.cpp/main.py", line 8, in <module>
    import llama_cpp
ModuleNotFoundError: No module named 'llama_cpp'

**Comment by ComputerGuy-github** [comment]
I think you have to install llama.cpp

**Comment by skyline9394** [comment]
Easy installation:

./run.sh
This should pull the repos and install the requirements. You will need llama.cpp build using make or cmake. The script above will try to do that.

After the initial run you can just run:

streamlit run main.py

what im missing here it dont say install anything?

**Comment by ComputerGuy-github** [comment]
Oh, Im not sure how you can fix that, I am not familiar with streamlit apps, I just saw the python error and came to a conclusion too quickly.

**Comment by kevkid** [comment]
fixed, have updated the run.sh.

you needed to do `pip install llama-cpp-python`

if you get build errors it seems like gcc 11 will fix that
```
sudo apt install gcc-11 g++-11 build-essential -y
CXX=g++-11  CC=gcc-11 pip install llama-cpp-python
```

https://github.com/oobabooga/text-generation-webui/issues/1534

**Comment by kevkid** [comment]
If you have further issues, feel free to open a new ticket
